version: 2
sources:
  - name: raw
    database: BI_CLASS
    schema: RAW
    tables:
      - name: CUSTOMER_DATA
      - name: PRODUCT_DATA
      - name: RESELLER_DATA
      - name: DATE_DATA
      - name: SALES_TERRITORY_DATA
      - name: SALES_DATA
      - name: SALES_ORDER_DATA
